spring:
  datasource:
    url: jdbc:h2:mem:springcoredb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql=true
    hibernate:
      ddl-auto: update
    generate-ddl: true
